name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/my-image:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-image:latest
          
    # steps:
    #   - name: Check out the repo
    #     uses: actions/checkout@v3
      
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    #   - name: Build and push Docker image
    #     uses: docker/build-push-action@v4
    #     with:
    #       context: DockerFileFolder/
    #       push: true
    #       tags: shivam0007/myspringbootapp:latest
          
